#define COMBO_TERM 30

#define USB_SUSPEND_WAKEUP_DELAY 0
#undef MOUSEKEY_MAX_SPEED
#define MOUSEKEY_MAX_SPEED 3

#undef MOUSEKEY_TIME_TO_MAX
#define MOUSEKEY_TIME_TO_MAX 40

#define NO_AUTO_SHIFT_TAB
#define NO_AUTO_SHIFT_SPECIAL
#define NO_AUTO_SHIFT_ALPHA
#define SERIAL_NUMBER "PWMDE/bv7m7D"
#define LAYER_STATE_16BIT
#define COMBO_COUNT 8

#define TAPPING_TERM_PER_KEY
#define MOUSE_EXTENDED_REPORT
#define NAVIGATOR_SCROLL_DIVIDER 24
#define RGB_MATRIX_STARTUP_SPD 60

