#define COMBO_TERM 30

#define USB_SUSPEND_WAKEUP_DELAY 0
#undef MOUSEKEY_MAX_SPEED
#define MOUSEKEY_MAX_SPEED 3

#undef MOUSEKEY_TIME_TO_MAX
#define MOUSEKEY_TIME_TO_MAX 40

#define NO_AUTO_SHIFT_TAB
#define NO_AUTO_SHIFT_SPECIAL
#define NO_AUTO_SHIFT_ALPHA
#define SERIAL_NUMBER "PWMDE/9DRPpL"
#define LAYER_STATE_16BIT
#define COMBO_COUNT 8

#define TAPPING_TERM_PER_KEY
#define MOUSE_EXTENDED_REPORT
#define POINTING_DEVICE_AUTO_MOUSE_ENABLE
#define AUTO_MOUSE_DEFAULT_LAYER 7
#define AUTO_MOUSE_TIME 800
#define AUTO_MOUSE_THRESHOLD 8
#define NAVIGATOR_SCROLL_INVERT
#define NAVIGATOR_SCROLL_DIVIDER 32
#define RGB_MATRIX_STARTUP_SPD 60

